// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkGnktfdcT1W92flJmuXLGGjMqfOzA-Xg',
    appId: '1:402215629825:web:8497ae1300e5798d013c00',
    messagingSenderId: '402215629825',
    projectId: 'fiscalnews-6a2d9',
    authDomain: 'fiscalnews-6a2d9.firebaseapp.com',
    storageBucket: 'fiscalnews-6a2d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Xlnya2nuvgx6IDaiAFCD6kWWb-eILwY',
    appId: '1:402215629825:android:ac39e276d28b6cb6013c00',
    messagingSenderId: '402215629825',
    projectId: 'fiscalnews-6a2d9',
    storageBucket: 'fiscalnews-6a2d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7fLPX3Lk5GABidZSlCZSD9T689eL6QxA',
    appId: '1:402215629825:ios:5c21f5209e39e8f9013c00',
    messagingSenderId: '402215629825',
    projectId: 'fiscalnews-6a2d9',
    storageBucket: 'fiscalnews-6a2d9.appspot.com',
    iosClientId: '402215629825-nprch24m6nq66krkfftucr706evlv2ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.app006P1',
  );
}
